version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: immigration-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PORT=5000
    volumes:
      # Monta datos desde el directorio padre si existen
      - ../4_data_analysis:/app/data:ro
    networks:
      - immigration-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend SvelteKit service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: immigration-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - immigration-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Nginx reverse proxy (opcional para producción)
  nginx:
    image: nginx:alpine
    container_name: immigration-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - immigration-network
    restart: unless-stopped
    profiles:
      - production

networks:
  immigration-network:
    driver: bridge

volumes:
  nginx_ssl:
    driver: local
