version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: immigration-backend-prod
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PORT=5000
    volumes:
      - ../4_data_analysis:/app/data:ro
    networks:
      - immigration-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: immigration-frontend-prod
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - immigration-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: immigration-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - immigration-network
    restart: unless-stopped
    profiles:
      - production

networks:
  immigration-network:
    driver: bridge
